//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int Id { get; set; }
        public System.DateTime DataInicial { get; set; }
        public System.DateTime DataFinal { get; set; }
        public Nullable<int> PacienteId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> MotivoId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Status Status { get; set; }
        public virtual Motivo Motivo { get; set; }
    }
}
