//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicacao
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int PacienteId { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataExclusao { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
