//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedica.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicamedicaEntities : DbContext
    {
        public clinicamedicaEntities()
            : base("name=clinicamedicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Medicacao> Medicacao { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
    }
}
